#ifndef ADC_CONFIG_H
#define ADC_CONFIG_H


#define ENABLE		1
#define DISABLE 	0


#define ADC_INTERRUPT		ENABLE
#define ADC_TIME_OUT 		10000


/*
options:

			ADMUX_REF_VOLATGE_AREF          
			ADMUX_REF_VOLATGE_AVCC          
			ADMUX_REF_VOLTAGE_INTERNAL_2_56 


*/


#define ADC_REF_VOLTAGE       ADMUX_REF_VOLATGE_AVCC



/*options:

			ADCSRA_PRESCALER_2         
			ADCSRA_PRESCALER_2_RESERVED
			ADCSRA_PRESCALER_4         
			ADCSRA_PRESCALER_8         
			ADCSRA_PRESCALER_16        
			ADCSRA_PRESCALER_32        
			ADCSRA_PRESCALER_64        
			ADCSRA_PRESCALER_128       


*/
#define ADC_PRESCALER         ADCSRA_PRESCALER_8


/*		
options	:	LEFT_ADJUST 
			RIGHT_ADJUST

*/
#define ADC_ADJUST            LEFT_ADJUST


/*		
options	:	ADC_8_BITS	
			ADC_10_BITS

*/
#define ADC_MODE			ADC_10_BITS

/*	max of 8	*/

#define ADC_NUMBER_OF_USED_CHANNELS    2

/*
options:
ADMUX_CHANNEL_SINGALE_ADCO                   
ADMUX_CHANNEL_SINGLE_ADC1                    
ADMUX_CHANNEL_SINGLE_ADC2                    
ADMUX_CHANNEL_SINGLE_ADC3                    
ADMUX_CHANNEL_SINGLE_ADC4                    
ADMUX_CHANNEL_SINGLE_ADC5                    
ADMUX_CHANNEL_SINGLE_ADC6                    
ADMUX_CHANNEL_SINGLE_ADC7                    
ADMUX_CHANNEL_DIFFERENTIAL_ADC0_ADC0_GAIN_10 
ADMUX_CHANNEL_DIFFERENTIAL_ADC1_ADC0_GAIN_10 
ADMUX_CHANNEL_DIFFERENTIAL_ADC0_ADC0_GAIN_200
ADMUX_CHANNEL_DIFFERENTIAL_ADC1_ADC0_GAIN_200
ADMUX_CHANNEL_DIFFERENTIAL_ADC2_ADC2_GAIN_10 
ADMUX_CHANNEL_DIFFERENTIAL_ADC3_ADC2_GAIN_10 
ADMUX_CHANNEL_DIFFERENTIAL_ADC2_ADC2_GAIN_200
ADMUX_CHANNEL_DIFFERENTIAL_ADC3_ADC2_GAIN_200
ADMUX_CHANNEL_DIFFERENTIAL_ADC0_ADC1_GAIN_1  
ADMUX_CHANNEL_DIFFERENTIAL_ADC1_ADC1_GAIN_1  
ADMUX_CHANNEL_DIFFERENTIAL_ADC2_ADC1_GAIN_1  
ADMUX_CHANNEL_DIFFERENTIAL_ADC3_ADC1_GAIN_1  
ADMUX_CHANNEL_DIFFERENTIAL_ADC4_ADC1_GAIN_1  
ADMUX_CHANNEL_DIFFERENTIAL_ADC5_ADC1_GAIN_1  
ADMUX_CHANNEL_DIFFERENTIAL_ADC6_ADC1_GAIN_1  
ADMUX_CHANNEL_DIFFERENTIAL_ADC7_ADC1_GAIN_1  
ADMUX_CHANNEL_DIFFERENTIAL_ADC0_ADC2_GAIN_1  
ADMUX_CHANNEL_DIFFERENTIAL_ADC1_ADC2_GAIN_1  
ADMUX_CHANNEL_DIFFERENTIAL_ADC2_ADC2_GAIN_1  
ADMUX_CHANNEL_DIFFERENTIAL_ADC3_ADC2_GAIN_1  
ADMUX_CHANNEL_DIFFERENTIAL_ADC4_ADC2_GAIN_1  
ADMUX_CHANNEL_DIFFERENTIAL_ADC5_ADC2_GAIN_1  
ADMUX_CHANNEL_SINGLE_122V                    
ADMUX_CHANNEL_SINGLE_0V                      


*/

#define ADC_FIRST_CHANNEL	ADMUX_CHANNEL_SINGLE_ADC2
#define ADC_SECOND_CHANNEL	ADMUX_CHANNEL_SINGLE_ADC1
#define ADC_THIRD_CHANNEL	ADMUX_CHANNEL_SINGLE_ADC1
#define ADC_FORTH_CHANNEL	ADMUX_CHANNEL_SINGLE_ADC1
#define ADC_FIFTH_CHANNEL	ADMUX_CHANNEL_SINGLE_ADC1
#define ADC_SIXTH_CHANNEL	ADMUX_CHANNEL_SINGLE_ADC1
#define ADC_SEVENTH_CHANNEL	ADMUX_CHANNEL_SINGLE_ADC1
#define ADC_EIGHTTH_CHANNEL	ADMUX_CHANNEL_SINGLE_ADC1


#endif
