/*	keypad rows pins configuration	*/



#define LEDMATRIX_ROW_PORT		'D'
#define LEDMATRIX_R0_PIN			0

#define LEDMATRIX_R1_PIN			1

#define LEDMATRIX_R2_PIN			2

#define LEDMATRIX_R3_PIN			3

#define LEDMATRIX_R4_PIN			4

#define LEDMATRIX_R5_PIN			5

#define LEDMATRIX_R6_PIN			6

#define LEDMATRIX_R7_PIN			7


/*	keypad coloums pins configuration	*/

#define LEDMATRIX_C0_RED_PORT		'C'
#define LEDMATRIX_C0_RED_PIN			0

#define LEDMATRIX_C1_RED_PORT		'C'
#define LEDMATRIX_C1_RED_PIN			2

#define LEDMATRIX_C2_RED_PORT		'C'
#define LEDMATRIX_C2_RED_PIN			4

#define LEDMATRIX_C3_RED_PORT		'C'
#define LEDMATRIX_C3_RED_PIN			6

#define LEDMATRIX_C4_RED_PORT		'A'
#define LEDMATRIX_C4_RED_PIN			0

#define LEDMATRIX_C5_RED_PORT		'A'
#define LEDMATRIX_C5_RED_PIN			2

#define LEDMATRIX_C6_RED_PORT		'A'
#define LEDMATRIX_C6_RED_PIN			4

#define LEDMATRIX_C7_RED_PORT		'A'
#define LEDMATRIX_C7_RED_PIN			6

#define LEDMATRIX_C0_YELLOW_PORT	'C'
#define LEDMATRIX_C0_YELLOW_PIN			1

#define LEDMATRIX_C1_YELLOW_PORT	'C'
#define LEDMATRIX_C1_YELLOW_PIN			3

#define LEDMATRIX_C2_YELLOW_PORT	'C'
#define LEDMATRIX_C2_YELLOW_PIN			5

#define LEDMATRIX_C3_YELLOW_PORT	'C'
#define LEDMATRIX_C3_YELLOW_PIN			7

#define LEDMATRIX_C4_YELLOW_PORT	'A'
#define LEDMATRIX_C4_YELLOW_PIN			1

#define LEDMATRIX_C5_YELLOW_PORT	'A'
#define LEDMATRIX_C5_YELLOW_PIN			3

#define LEDMATRIX_C6_YELLOW_PORT	'A'
#define LEDMATRIX_C6_YELLOW_PIN			5

#define LEDMATRIX_C7_YELLOW_PORT	'A'
#define LEDMATRIX_C7_YELLOW_PIN			7


/*how many coloums do you need with a max of 4*/

#define	LEDMATRIX_COL_NUM	8

/*how many rows do you need with a max of 4*/

#define	LEDMATRIX_ROW_NUM	8

/*	CHOOSE THE PINS THAT YOU NEED	*/

#define LEDMATRIX_COL_YELLOW_PINS	{LEDMATRIX_C0_YELLOW_PIN,LEDMATRIX_C1_YELLOW_PIN,LEDMATRIX_C2_YELLOW_PIN,LEDMATRIX_C3_YELLOW_PIN,LEDMATRIX_C4_YELLOW_PIN,LEDMATRIX_C5_YELLOW_PIN,LEDMATRIX_C6_YELLOW_PIN,LEDMATRIX_C7_YELLOW_PIN}
#define LEDMATRIX_COL_RED_PINS		{LEDMATRIX_C0_RED_PIN,LEDMATRIX_C1_RED_PIN,LEDMATRIX_C2_RED_PIN,LEDMATRIX_C3_RED_PIN,LEDMATRIX_C4_RED_PIN,LEDMATRIX_C5_RED_PIN,LEDMATRIX_C6_RED_PIN,LEDMATRIX_C7_RED_PIN}
#define LEDMATRIX_ROW_PINS			{LEDMATRIX_R0_PIN,LEDMATRIX_R1_PIN,LEDMATRIX_R2_PIN,LEDMATRIX_R3_PIN,LEDMATRIX_R4_PIN,LEDMATRIX_R5_PIN,LEDMATRIX_R6_PIN,LEDMATRIX_R7_PIN}

/*	CHOOSE THE PORTS THAT YOU NEED	*/
#define LEDMATRIX_COL_YELLOW_PORTS	{LEDMATRIX_C0_YELLOW_PORT,LEDMATRIX_C1_YELLOW_PORT,LEDMATRIX_C2_YELLOW_PORT,LEDMATRIX_C3_YELLOW_PORT,LEDMATRIX_C4_YELLOW_PORT,LEDMATRIX_C5_YELLOW_PORT,LEDMATRIX_C6_YELLOW_PORT,LEDMATRIX_C7_YELLOW_PORT}
#define LEDMATRIX_COL_RED_PORTS		{LEDMATRIX_C0_RED_PORT,LEDMATRIX_C1_RED_PORT,LEDMATRIX_C2_RED_PORT,LEDMATRIX_C3_RED_PORT,LEDMATRIX_C4_RED_PORT,LEDMATRIX_C5_RED_PORT,LEDMATRIX_C6_RED_PORT,LEDMATRIX_C7_RED_PORT}
#define LEDMATRIX_ROW_PORTS			{LEDMATRIX_R0_PORT,LEDMATRIX_R1_PORT,LEDMATRIX_R2_PORT,LEDMATRIX_R3_PORT,LEDMATRIX_R4_PORT,LEDMATRIX_R5_PORT,LEDMATRIX_R6_PORT,LEDMATRIX_R7_PORT}
