#define	conc(b7,b6,b5,b4,b3,b2,b1,b0)				concHelp(b7,b6,b5,b4,b3,b2,b1,b0)

#define concHelp(b7,b6,b5,b4,b3,b2,b1,b0)		0b##b7##b6##b5##b4##b3##b2##b1##b0

#define PORTA_DIR														conc(PORTA_PIN7_DIR,PORTA_PIN6_DIR,PORTA_PIN5_DIR,PORTA_PIN4_DIR,PORTA_PIN3_DIR,PORTA_PIN2_DIR,PORTA_PIN1_DIR,PORTA_PIN0_DIR)

#define PORTB_DIR														conc(PORTB_PIN7_DIR,PORTB_PIN6_DIR,PORTB_PIN5_DIR,PORTB_PIN4_DIR,PORTB_PIN3_DIR,PORTB_PIN2_DIR,PORTB_PIN1_DIR,PORTB_PIN0_DIR)

#define PORTC_DIR														conc(PORTC_PIN7_DIR,PORTC_PIN6_DIR,PORTC_PIN5_DIR,PORTC_PIN4_DIR,PORTC_PIN3_DIR,PORTC_PIN2_DIR,PORTC_PIN1_DIR,PORTC_PIN0_DIR)

#define PORTD_DIR														conc(PORTD_PIN7_DIR,PORTD_PIN6_DIR,PORTD_PIN5_DIR,PORTD_PIN4_DIR,PORTD_PIN3_DIR,PORTD_PIN2_DIR,PORTD_PIN1_DIR,PORTD_PIN0_DIR)

#define PORTA_INITIALVAL										conc(PORTA_PIN7_INITIALVAL,PORTA_PIN6_INITIALVAL,PORTA_PIN5_INITIALVAL,PORTA_PIN4_INITIALVAL,PORTA_PIN3_INITIALVAL,PORTA_PIN2_INITIALVAL,PORTA_PIN1_INITIALVAL,PORTA_PIN0_INITIALVAL)

#define PORTB_INITIALVAL										conc(PORTB_PIN7_INITIALVAL,PORTB_PIN6_INITIALVAL,PORTB_PIN5_INITIALVAL,PORTB_PIN4_INITIALVAL,PORTB_PIN3_INITIALVAL,PORTB_PIN2_INITIALVAL,PORTB_PIN1_INITIALVAL,PORTB_PIN0_INITIALVAL)

#define PORTC_INITIALVAL										conc(PORTC_PIN7_INITIALVAL,PORTC_PIN6_INITIALVAL,PORTC_PIN5_INITIALVAL,PORTC_PIN4_INITIALVAL,PORTC_PIN3_INITIALVAL,PORTC_PIN2_INITIALVAL,PORTC_PIN1_INITIALVAL,PORTC_PIN0_INITIALVAL)

#define PORTD_INITIALVAL										conc(PORTD_PIN7_INITIALVAL,PORTD_PIN6_INITIALVAL,PORTD_PIN5_INITIALVAL,PORTD_PIN4_INITIALVAL,PORTD_PIN3_INITIALVAL,PORTD_PIN2_INITIALVAL,PORTD_PIN1_INITIALVAL,PORTD_PIN0_INITIALVAL)
